---
version: '2.2'
services:
  demo:
    image: demo
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "mysql://root:pass@mysql:3306/users"
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
